// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Report.API.Data;

#nullable disable

namespace Report.API.Migrations
{
    [DbContext(typeof(ReportDbContext))]
    partial class ReportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Report.API.Models.ShiftReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlertasAtendidas")
                        .HasColumnType("int");

                    b.Property<int>("AlertasResueltas")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinTurno")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuardiaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InicioTurno")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreGuardia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreZona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TiempoRespuestaPromedio")
                        .HasColumnType("float");

                    b.Property<int>("ZonaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuardiaId")
                        .HasDatabaseName("IX_ShiftReports_GuardiaId");

                    b.HasIndex("InicioTurno")
                        .HasDatabaseName("IX_ShiftReports_InicioTurno");

                    b.HasIndex("ZonaId")
                        .HasDatabaseName("IX_ShiftReports_ZonaId");

                    b.HasIndex("ZonaId", "InicioTurno")
                        .HasDatabaseName("IX_ShiftReports_ZonaId_InicioTurno");

                    b.ToTable("ShiftReports");
                });
#pragma warning restore 612, 618
        }
    }
}
