// <auto-generated />
using System;
using Campus.Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Campus.Service.Migrations
{
    [DbContext(typeof(CampusDbContext))]
    [Migration("20260511015307_InitialCampus")]
    partial class InitialCampus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Campus.Service.Models.Guard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreGuardia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("ZonaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZonaId");

                    b.ToTable("Guards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "En Servicio",
                            NombreGuardia = "Guardia Pedro",
                            UsuarioId = 2,
                            ZonaId = 1
                        });
                });

            modelBuilder.Entity("Campus.Service.Models.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoordenadasJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Azul",
                            CoordenadasJson = "[{\"lat\":-1.266403, \"lng\":-78.625312}, {\"lat\":-1.267693, \"lng\":-78.624075}, {\"lat\":-1.266470, \"lng\":-78.624768}]",
                            Nombre = "Zona 1"
                        },
                        new
                        {
                            Id = 2,
                            Color = "Verde",
                            CoordenadasJson = "[{\"lat\":-1.267714, \"lng\":-78.625654}, {\"lat\":-1.268798, \"lng\":-78.624850}, {\"lat\":-1.268746, \"lng\":-78.625922}]",
                            Nombre = "Zona 2"
                        },
                        new
                        {
                            Id = 3,
                            Color = "Naranja",
                            CoordenadasJson = "[{\"lat\":-1.268034, \"lng\":-78.623935}, {\"lat\":-1.266572, \"lng\":-78.623173}, {\"lat\":-1.266471, \"lng\":-78.624359}]",
                            Nombre = "Zona 3"
                        },
                        new
                        {
                            Id = 4,
                            Color = "Rojo",
                            CoordenadasJson = "[{\"lat\":-1.268747, \"lng\":-78.625948}, {\"lat\":-1.270194, \"lng\":-78.622425}, {\"lat\":-1.270364, \"lng\":-78.626346}]",
                            Nombre = "Zona 4"
                        });
                });

            modelBuilder.Entity("Campus.Service.Models.Guard", b =>
                {
                    b.HasOne("Campus.Service.Models.Zone", "Zona")
                        .WithMany()
                        .HasForeignKey("ZonaId");

                    b.Navigation("Zona");
                });
#pragma warning restore 612, 618
        }
    }
}
