// <auto-generated />
using System;
using Alerts.Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alerts.Service.Migrations
{
    [DbContext(typeof(AlertsDbContext))]
    [Migration("20260524181138_AddAlertIndexes")]
    partial class AddAlertIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Alerts.Service.Models.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorZona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Facultad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaAsumida")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCerrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEnCamino")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaResuelta")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GuardiaAsignadoId")
                        .HasColumnType("int");

                    b.Property<string>("GuardiaAsignadoNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreZona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("ZonaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_Alerts_Estado");

                    b.HasIndex("FechaHora")
                        .HasDatabaseName("IX_Alerts_FechaHora");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("IX_Alerts_UsuarioId");

                    b.HasIndex("ZonaId")
                        .HasDatabaseName("IX_Alerts_ZonaId");

                    b.HasIndex("ZonaId", "FechaHora")
                        .HasDatabaseName("IX_Alerts_ZonaId_FechaHora");

                    b.ToTable("Alerts");
                });
#pragma warning restore 612, 618
        }
    }
}
